### ISSUE TITLE
Question about waiting time on wrong PIN

### ISSUE THREAD

**Issue by mizzunet** [androidmalware/android_hid#10]
How this works? I mean, Androdi has a basic security that is when wrong PIN/Pattern entered, we got to wait 30 seconds to enter next then 30 seconds for each wrong try after that. How is this method gonna get over it I wonder?

**Comment by superbonaci** [comment]
Yeah the idea is to know if because of using this HID device you have unlimited attempts, or if is the same as someone entering the PIN physically.

**Comment by mizzunet** [comment]
Cool
